[project]
name = "pynigma"
version = "0.1.0"
description = "An implementation of the Enigma cypher device"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv]
dev-dependencies = [
    "ruff>=0.7.2",
]
